### ISSUE TITLE
Dataset to run the model

### ISSUE THREAD

**Issue by Rajmehta123** [eliasbaumann/BERT_stock_forecasting#1]
Hello @eliasbaumann 
This project looks very interesting. But when I try to run the run.py, it throws an error: 'FileNotFoundError: [Errno 2] No such file or directory: './all_upto_2019-08-29.csv''.

Where can I find this file? Or what is the content for this file? Is it the ticker symbol/news?

**Comment by eliasbaumann** [comment]
Hey @Rajmehta123, thanks for the interest in this repo. The dataset required is not public and you will not be able to request access. However, you can likely build your own dataset consisting of stock news articles.

**Comment by Rajmehta123** [comment]
@eliasbaumann What does the dataset look like? How is it indexed? Is the news consumed daily and merge the news date with the closing price date? I have the news data but if I can get the snapshot of how to use data, it will help in running the model. Not knowing the data format will render the model unusable.

**Comment by eliasbaumann** [comment]
"all_upto_2019-08-29.csv" consists of "Symbols", "Article_time" and "text" column. If you check the preprocessing.py in the  pre_process_news function you probably figure out how to setup your own dataset the same way. Please understand that this github repository is not meant to be a general tool for anyone but rather is a setup for university students who want to work on similar problems for their masters thesis.
